apiVersion: v1
kind: Service
metadata:
  name: ssp-service
  labels:
    app: ssp
spec:
  selector:
    app: ssp
  ports:
  - port: 8080
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssp-deployment
  labels:
    app: ssp
spec:
  spec:
  selector:
    matchLabels:
      app: ssp
  replicas: 1
  template:
    metadata:
      labels:
        app: ssp
    spec:
      containers:
      - name: selfservicepassword
        image: zzorica/selfservicepassword:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: SSP_LOGO
          value: ""
        - name: SSP_BACKGROUND_IMAGE
          value: ""
        - name: SSP_LDAP_URL
          value: "ldap://ldap-service.default"
        - name: SSP_LDAP_BINDDN
          value: "cn=admin,dc=example,dc=com"
        - name: SSP_LDAP_BINDPW
          valueFrom:
            secretKeyRef:
              name: admin-password
              key: password
        - name: SSP_LDAP_BASE
          value: "dc=example,dc=com"
        - name: SSP_LDAP_LOGIN_ATTRIBUTE
          value: "uid"
        - name: SSP_LDAP_FULLNAME_ATTRIBUTE
          value: "cn"
        - name: SSP_LDAP_FILTER
          value: "(&(objectClass=person)(uid={login}))"
        - name: SSP_KEYPHRASE
          value: "ooP5Ais3Um2cai5phaighahg2tetai7u"
        - name: SSP_MAIL_FROM
          value: "noreply@example.com"
        - name: SSP_MAIL_FROM_NAME
          value: "Password Reset"
        - name: SSP_MAIL_SMTP_HOST
          value: "smtp.gmail.com"
        - name: SSP_MAIL_SMTP_AUTH
          value: "true"
        - name: SSP_MAIL_SMTP_USER
          valueFrom:
            secretKeyRef:
              name: smtp-password
              key: user
        - name: SSP_MAIL_SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: smtp-password
              key: password
